### PR TITLE
Missing override keyword

### PR DESCRIPTION
**Pull request by mbudiu-vmw**
Looks like the lastest merge broke the build for MacOs. I hope that this commit fixes it.

### CODE REVIEW

**Comment by mbudiu-vmw** [comment]
It looks like this is not enough. There is some problem with the bison-generated files on MacOS.

**Comment by mbudiu-vmw** [comment]
The compilation complains about a missing header file that is generated by bison, but the corresponding bison invocation hasn't been done yet. So there must be something wrong with the dependencies in the Makefile.

**Comment by mbudiu-vmw** [comment]
The error is 
```
[ 17%] Building CXX object ir/CMakeFiles/ir.dir/unified_ir_srcs_1.cpp.o
In file included from /Users/runner/work/p4c/p4c/build/frontends/unified_frontend_sources_1.cpp:2:
In file included from /Users/runner/work/p4c/p4c/frontends/common/applyOptionsPragmas.cpp:19:
In file included from /Users/runner/work/p4c/p4c/frontends/parsers/parserDriver.h:25:
/Users/runner/work/p4c/p4c/frontends/parsers/p4/abstractP4Lexer.hpp:4:10: fatal error: 'frontends/parsers/p4/p4parser.hpp' file not found
#include "frontends/parsers/p4/p4parser.hpp"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
however, on my machine there is clearly a dependence in frontends/CMakeFiles/frontend.dir/depend.make:
```
frontends/CMakeFiles/frontend.dir/unified_frontend_sources_1.cpp.o: frontends/parsers/p4/p4parser.hpp
```

**Comment by mbudiu-vmw** [comment]
In the builds that pass this kind of message shows up in the logs:
```
2021-03-31T07:41:47.2431290Z Scanning dependencies of target update_includes
```
However, in the failing builds this kind of message does not appear.
So the dependencies are not computed.

**Comment by fruffy** [comment]
It is only the unified build that fails. Really strange.

**Comment by fruffy** [comment]
Okay so I just tried this on an older commit on my fork and it still failed. So none of the recent commits is at fault. What I can see is that the mac-os image [upgraded](https://github.com/actions/virtual-environments/commit/9d6f73f02d2cb3d2793ed5ce1daec6eb2c63e29d#diff-7a1606bd717fc0cf55f9419157117d9ca306f91bd2fdfc294720687d7be1b2c7R100) to CMake 3.20 3 days ago. Maybe this could be an issue. I have not tried building p4c with a CMake 3.20 version

**Comment by fruffy** [comment]
Yup, I just tried to compile this on a fresh build on Linux with CMake 3.20 and it also failed. I feel like [this](https://cmake.org/cmake/help/latest/release/3.20.html#generators) may be at fault. Unfortunately, I do not have much time to debug this right now.

**Review by fruffy — APPROVED** [review]
